
app = 'bruce-irakoze'
primary_region = 'otp'

[build]


[mounts]
  source = "postgres"
  destination = "/postgres-volume"

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
